version: "3"
services:
  app:
    ports:
      # Проброс портов
      - "8080:8080"
    command: npm run dev

    volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      - ./app:/app
