version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: makmakkerti/devops-for-programmers-project-74:latest
    environment:
      PGHOST: 'db'
      PGDATABASE: 'postgres'
      PGUSER: 'postgres'
      PGPASSWORD: 'password'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: